# Ruff configuration
target-version = "py38"
line-length = 140

[lint]
select = ["E", "F", "I", "W", "N", "D", "UP", "S", "B"]
ignore = ["D203", "D213"]

[lint.per-file-ignores]
"__init__.py" = ["F401", "E402"]
"tests/*" = ["S101", "D"]

[lint.isort]
known-first-party = ["linkedin_games_scraper"]

[lint.flake8-quotes]
docstring-quotes = "double"
